name: Advent of code

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      id: restore-cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

    - name: install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
      if: steps.restore-cache.outputs.cache-hit != 'true'

    - name: run tests
      run: |
        poetry run py.test

    - name: solve
      run: |
        for day in day*.py; do
          echo "****** $day ******"
          poetry run python $day
        done
